# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Hook set for Python formatting & unused-import removal
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
        types: [python]
      - id: ruff-format
        types: [python]

  # Hook set for JavaScript / TypeScript lint-fix (including unused-imports)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.25.1
    hooks:
      - id: eslint
        args: ["--cache", "--fix"]
        files: "web/.*\\.(js|jsx|ts|tsx)$"
        additional_dependencies:
          - "eslint@8.56.0"
          - "typescript@5.2.2"
          - "eslint-config-next@13.5.1"
          - "eslint-plugin-import@2.27.5"
          - "eslint-plugin-unused-imports@3.1.0"

  # Hook set for JavaScript / TypeScript formatting via Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        files: "\\.(js|jsx|ts|tsx|json|css|scss|md|html|yml|yaml)$"

  # Local repository hooks (existing & custom project-specific)
  - repo: local
    hooks:
      # Regenerate uv.lock if pyproject.toml changed
      - id: update-uv-lock
        name: Update uv.lock
        entry: bash -c 'uv pip compile pyproject.toml -o uv.lock && git add uv.lock'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^pyproject\.toml$
# You can add other hooks here, e.g., for Ruff:
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     # Find the latest tag/rev: https://github.com/astral-sh/ruff-pre-commit/releases
#     rev: v0.5.5
#     hooks:
#       - id: ruff
#         args: [--fix]
#       - id: ruff-format
