# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
      - id: update-uv-lock
        name: Update uv.lock
        # Regenerate uv.lock if pyproject.toml changed
        entry: bash -c 'uv pip compile pyproject.toml -o uv.lock && git add uv.lock'
        language: system
        pass_filenames: false
        stages: [commit]
        files: ^pyproject\.toml$ # Only run if pyproject.toml itself is changing

# You can add other hooks here, e.g., for Ruff:
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     # Find the latest tag/rev: https://github.com/astral-sh/ruff-pre-commit/releases
#     rev: v0.5.5
#     hooks:
#       - id: ruff
#         args: [--fix]
#       - id: ruff-format 