"""Add shipping_price to Transaction

Revision ID: 019da03ebf26
Revises: f17b30a7005d
Create Date: 2025-02-22 01:11:34.502319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019da03ebf26'
down_revision: Union[str, None] = 'f17b30a7005d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('_shipping_price_amount', sa.Numeric(scale=2), server_default='0.00', nullable=False))
    op.add_column('transaction', sa.Column('_shipping_price_currency', sa.String(), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', '_shipping_price_currency')
    op.drop_column('transaction', '_shipping_price_amount')
    # ### end Alembic commands ###
