"""empty message

Revision ID: 09330d1456d2
Revises: 
Create Date: 2025-02-25 01:27:23.841581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09330d1456d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('currency', sa.String(), server_default='USD', nullable=False))
    op.drop_column('transaction', 'currency_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'currency')
    # ### end Alembic commands ###
