"""Remove SKULatestPriceData, SKUListingSnapshot, SKUPriceSnapshot models and tables

Revision ID: 18be0731b7c8
Revises: b5077ca26a88
Create Date: 2025-05-17 03:51:41.171558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "18be0731b7c8"
down_revision: Union[str, None] = "b5077ca26a88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sku_latest_price_data")
    op.drop_table("sku_price_snapshot")
    op.drop_table("sku_listing_snapshot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_listing_snapshot",
        sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["sku_price_snapshot_job.id"],
            name="sku_listing_snapshot_job_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name="sku_listing_snapshot_sku_id_fkey"
        ),
        sa.PrimaryKeyConstraint("sku_id", "job_id", name="sku_listing_snapshot_pkey"),
    )
    op.create_table(
        "sku_price_snapshot",
        sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "_lowest_listing_price_amount",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "_lowest_listing_price_currency",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "_market_price_amount", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "_market_price_currency", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["sku_price_snapshot_job.id"],
            name="sku_price_snapshot_job_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name="sku_price_snapshot_sku_id_fkey"
        ),
        sa.PrimaryKeyConstraint("sku_id", "job_id", name="sku_price_snapshot_pkey"),
    )
    op.create_table(
        "sku_latest_price_data",
        sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "lowest_listing_price_amount",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "market_price_amount", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name="sku_latest_price_data_sku_id_fkey"
        ),
        sa.PrimaryKeyConstraint("sku_id", name="sku_latest_price_data_pkey"),
    )
    # ### end Alembic commands ###
