"""remove language from product variant

Revision ID: 2ea948727dbe
Revises: e4e9a26ad6ac
Create Date: 2025-10-29 10:59:05.622102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ea948727dbe"
down_revision: Union[str, None] = "e4e9a26ad6ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_variant_printing_language"), table_name="product_variant"
    )
    op.drop_constraint(
        op.f("uq_product_variant_product_printing_language"),
        "product_variant",
        type_="unique",
    )
    op.create_index(
        "ix_product_variant_printing_id",
        "product_variant",
        ["printing_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_product_variant_product_printing",
        "product_variant",
        ["product_id", "printing_id"],
    )
    op.drop_constraint(
        op.f("product_variant_language_id_fkey"), "product_variant", type_="foreignkey"
    )
    op.drop_column("product_variant", "language_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variant",
        sa.Column("language_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("product_variant_language_id_fkey"),
        "product_variant",
        "language",
        ["language_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_product_variant_product_printing", "product_variant", type_="unique"
    )
    op.drop_index("ix_product_variant_printing_id", table_name="product_variant")
    op.create_unique_constraint(
        op.f("uq_product_variant_product_printing_language"),
        "product_variant",
        ["product_id", "printing_id", "language_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_product_variant_printing_language"),
        "product_variant",
        ["printing_id", "language_id"],
        unique=False,
    )
    # ### end Alembic commands ###
