"""create sku_market_data_sync_state; create buy_decision; create sales_listing with dedupe unique index

Revision ID: 3e58625477c4
Revises: 61ef3d11077e
Create Date: 2025-09-13 16:34:19.507392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from core.models.types import TextEnum
from core.models.price import Marketplace
from core.models.decisions import Decision

# revision identifiers, used by Alembic.
revision: str = "3e58625477c4"
down_revision: Union[str, None] = "61ef3d11077e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_market_data_sync_state",
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("marketplace", TextEnum(Marketplace), nullable=False),
        sa.Column("last_sales_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("sku_id", "marketplace"),
    )
    op.create_table(
        "buy_decision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("decision", TextEnum(Decision), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("buy_vwap", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "expected_resale_net", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("asof_listings", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asof_sales", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sales_listing",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace", TextEnum(Marketplace), nullable=False),
        sa.Column("sale_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("shipping_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sale_price > 0", name="ck_sales_listing_price_gt_zero"),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sales_listing_date",
        "sales_listing",
        [sa.literal_column("sale_date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_sales_listing_sku_marketplace_date",
        "sales_listing",
        ["sku_id", "marketplace", sa.literal_column("sale_date DESC")],
        unique=False,
    )
    op.create_index(
        "ux_sales_listing_sku_mkt_date_price_ship_qty",
        "sales_listing",
        [
            "sku_id",
            "marketplace",
            "sale_date",
            "sale_price",
            sa.literal_column("coalesce(shipping_price, -1)"),
            "quantity",
        ],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_sales_listing_sku_mkt_date_price_ship_qty", table_name="sales_listing"
    )
    op.drop_index("ix_sales_listing_sku_marketplace_date", table_name="sales_listing")
    op.drop_index("ix_sales_listing_date", table_name="sales_listing")
    op.drop_table("sales_listing")
    op.drop_table("buy_decision")
    op.drop_table("sku_market_data_sync_state")
    # ### end Alembic commands ###
