"""add composite ix_sku_price_snapshot_sku_id_dt_desc to SKUPriceDataSnapshot

Revision ID: 4811425b2f6f
Revises: beb965545bec
Create Date: 2025-05-18 23:20:50.240949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4811425b2f6f"
down_revision: Union[str, None] = "beb965545bec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_sku_price_snapshot_sku_id_dt_desc",
        "sku_price_data_snapshot",
        ["sku_id", sa.literal_column("snapshot_datetime DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sku_price_snapshot_sku_id_dt_desc", table_name="sku_price_data_snapshot"
    )
    # ### end Alembic commands ###
