"""empty message

Revision ID: 61ef3d11077e
Revises: bca083e8ed31
Create Date: 2025-08-31 23:55:00.182382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.models.types import TextEnum
from core.models.price import Marketplace


# revision identifiers, used by Alembic.
revision: str = "61ef3d11077e"
down_revision: Union[str, None] = "bca083e8ed31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_listing_data_refresh_priority",
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace", TextEnum(Marketplace), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uptrend_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("breakout_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("value_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("activity_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "snapshot_score_raw", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.Column("snapshot_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("sales_events_count", sa.Integer(), nullable=False),
        sa.Column("staleness_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("priority_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
        ),
        sa.PrimaryKeyConstraint("sku_id", "marketplace"),
    )
    op.create_index(
        "ix_sku_listing_data_refresh_priority_score",
        "sku_listing_data_refresh_priority",
        ["marketplace", sa.literal_column("priority_score DESC")],
        unique=False,
    )
    op.create_index(
        "ix_sku_listing_data_refresh_priority_sku_id",
        "sku_listing_data_refresh_priority",
        ["sku_id"],
        unique=False,
    )
    # Manual constraints not detected by autogenerate
    op.create_check_constraint(
        "ck_sku_latest_price_total_gt_zero",
        "sku_latest_price",
        "lowest_listing_price_total > 0",
    )
    op.create_check_constraint(
        "ck_sku_price_data_snapshot_price_gt_zero",
        "sku_price_data_snapshot",
        "lowest_listing_price_total > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_sku_price_data_snapshot_price_gt_zero",
        "sku_price_data_snapshot",
        type_="check",
    )
    op.drop_constraint(
        "ck_sku_latest_price_total_gt_zero", "sku_latest_price", type_="check"
    )
    op.drop_index(
        "ix_sku_listing_data_refresh_priority_sku_id",
        table_name="sku_listing_data_refresh_priority",
    )
    op.drop_index(
        "ix_sku_listing_data_refresh_priority_score",
        table_name="sku_listing_data_refresh_priority",
    )
    op.drop_table("sku_listing_data_refresh_priority")
    # ### end Alembic commands ###
