"""remove redundant index, keep only covering index

Revision ID: 636fbe83f6e9
Revises: 811760d1d175
Create Date: 2025-05-23 01:13:25.421788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "636fbe83f6e9"
down_revision: Union[str, None] = "811760d1d175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sku_price_snapshot_sku_id_dt_desc", table_name="sku_price_data_snapshot"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_sku_price_snapshot_sku_id_dt_desc",
        "sku_price_data_snapshot",
        ["sku_id", sa.literal_column("snapshot_datetime DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
