"""create inventory snapshot table

Revision ID: 6702d39d0232
Revises: be0a0c7ba16a
Create Date: 2025-04-26 10:44:17.664225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6702d39d0232"
down_revision: Union[str, None] = "be0a0c7ba16a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_market_value", sa.Float(), nullable=False),
        sa.Column("unrealised_profit", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory_snapshot")
    # ### end Alembic commands ###
