"""Add nullable product.ebay_product_id column with index.

Revision ID: 87e49cd60f27
Revises: f009ba678a41
Create Date: 2025-09-23 00:43:33.473774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87e49cd60f27"
down_revision: Union[str, None] = "f009ba678a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("ebay_product_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_product_ebay_product_id"), "product", ["ebay_product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_ebay_product_id"), table_name="product")
    op.drop_column("product", "ebay_product_id")
    # ### end Alembic commands ###
