"""create_sku_price_data_snapshot_table_with_job_id

Revision ID: 9c65c452f9c1
Revises: 18be0731b7c8
Create Date: 2025-05-17 12:39:16.005382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c65c452f9c1"
down_revision: Union[str, None] = "18be0731b7c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_price_data_snapshot",
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "lowest_listing_price_total",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["sku_price_snapshot_job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
        ),
        sa.PrimaryKeyConstraint("sku_id", "snapshot_datetime"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sku_price_data_snapshot")
    # ### end Alembic commands ###
