"""add_users_table_and_nullable_user_foreign_keys

Revision ID: a2e15da47a94
Revises: 92516477a264
Create Date: 2025-07-20 03:03:55.698932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2e15da47a94"
down_revision: Union[str, None] = "92516477a264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("inventory_snapshot", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "inventory_snapshot", "users", ["user_id"], ["id"])
    op.add_column("line_item", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "line_item", "users", ["user_id"], ["id"])
    op.add_column(
        "line_item_consumption", sa.Column("user_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(None, "line_item_consumption", "users", ["user_id"], ["id"])
    op.add_column("platform", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "platform", "users", ["user_id"], ["id"])
    op.add_column("transaction", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "transaction", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "user_id")
    op.drop_constraint(None, "platform", type_="foreignkey")
    op.drop_column("platform", "user_id")
    op.drop_constraint(None, "line_item_consumption", type_="foreignkey")
    op.drop_column("line_item_consumption", "user_id")
    op.drop_constraint(None, "line_item", type_="foreignkey")
    op.drop_column("line_item", "user_id")
    op.drop_constraint(None, "inventory_snapshot", type_="foreignkey")
    op.drop_column("inventory_snapshot", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
