"""Remove catalog_id from Condition and Language tables

Revision ID: b5077ca26a88
Revises: 1a01b5e0bfb2
Create Date: 2025-05-17 01:37:59.148358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5077ca26a88"
down_revision: Union[str, None] = "1a01b5e0bfb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_condition_catalog_id_tcgplayer_id", "condition", type_="unique"
    )
    op.create_unique_constraint(
        "uq_condition_tcgplayer_id", "condition", ["tcgplayer_id"]
    )
    op.drop_constraint("condition_catalog_id_fkey", "condition", type_="foreignkey")
    op.drop_column("condition", "catalog_id")
    op.drop_constraint(
        "uq_language_catalog_id_tcgplayer_id", "language", type_="unique"
    )
    op.create_unique_constraint(
        "uq_language_tcgplayer_id", "language", ["tcgplayer_id"]
    )
    op.drop_constraint("language_catalog_id_fkey", "language", type_="foreignkey")
    op.drop_column("language", "catalog_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language",
        sa.Column("catalog_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "language_catalog_id_fkey", "language", "catalog", ["catalog_id"], ["id"]
    )
    op.drop_constraint("uq_language_tcgplayer_id", "language", type_="unique")
    op.create_unique_constraint(
        "uq_language_catalog_id_tcgplayer_id",
        "language",
        ["catalog_id", "tcgplayer_id"],
    )
    op.add_column(
        "condition",
        sa.Column("catalog_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "condition_catalog_id_fkey", "condition", "catalog", ["catalog_id"], ["id"]
    )
    op.drop_constraint("uq_condition_tcgplayer_id", "condition", type_="unique")
    op.create_unique_constraint(
        "uq_condition_catalog_id_tcgplayer_id",
        "condition",
        ["catalog_id", "tcgplayer_id"],
    )
    # ### end Alembic commands ###
