"""Add sku_latest_price table

Revision ID: bca083e8ed31
Revises: f3bc3663d09e
Create Date: 2025-08-30 11:30:00.727845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.models.types import TextEnum
from core.models.price import Marketplace


# revision identifiers, used by Alembic.
revision: str = "bca083e8ed31"
down_revision: Union[str, None] = "f3bc3663d09e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_latest_price",
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace", TextEnum(Marketplace), nullable=False),
        sa.Column(
            "lowest_listing_price_total",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
        ),
        sa.PrimaryKeyConstraint("sku_id", "marketplace"),
    )
    op.create_index(
        "ix_sku_latest_price_marketplace_updated_at",
        "sku_latest_price",
        ["marketplace", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sku_latest_price_marketplace_updated_at", table_name="sku_latest_price"
    )
    op.drop_table("sku_latest_price")
    # ### end Alembic commands ###
