"""update_sku_price_snapshot_job_add_start_end_time

Revision ID: beb965545bec
Revises: 9c65c452f9c1
Create Date: 2025-05-17 14:18:06.580388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "beb965545bec"
down_revision: Union[str, None] = "9c65c452f9c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sku_price_snapshot_job",
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "sku_price_snapshot_job",
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("sku_price_snapshot_job", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sku_price_snapshot_job",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sku_price_snapshot_job", "end_time")
    op.drop_column("sku_price_snapshot_job", "start_time")
    # ### end Alembic commands ###
