"""empty message

Revision ID: c75876a39c72
Revises: 4d37d2a7f1dd
Create Date: 2025-03-07 22:58:51.177903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75876a39c72'
down_revision: Union[str, None] = '4d37d2a7f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('tax_amount', sa.Numeric(scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'tax_amount')
    # ### end Alembic commands ###
