"""remove_sku_price_snapshot_job_table

Revision ID: c856f91227cd
Revises: e3c995f34f66
Create Date: 2025-05-20 23:22:44.060985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c856f91227cd"
down_revision: Union[str, None] = "e3c995f34f66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "sku_price_data_snapshot_job_id_fkey",
        "sku_price_data_snapshot",
        type_="foreignkey",
    )
    op.drop_column("sku_price_data_snapshot", "job_id")
    op.drop_table("sku_price_snapshot_job")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_price_snapshot_job",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="sku_price_snapshot_job_pkey"),
    )
    op.add_column(
        "sku_price_data_snapshot",
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "sku_price_data_snapshot_job_id_fkey",
        "sku_price_data_snapshot",
        "sku_price_snapshot_job",
        ["job_id"],
        ["id"],
    )
    # ### end Alembic commands ###
