"""add optimized index for latest buy decision per sku query

Revision ID: cab2d0620b52
Revises: 3e58625477c4
Create Date: 2025-09-13 17:57:36.688377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cab2d0620b52"
down_revision: Union[str, None] = "3e58625477c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_buy_decision_latest_per_sku",
        "buy_decision",
        ["sku_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("decision = 'BUY'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_buy_decision_latest_per_sku",
        table_name="buy_decision",
        postgresql_where=sa.text("decision = 'BUY'"),
    )
    # ### end Alembic commands ###
