"""create product variant table

Revision ID: cd4fb2cee067

Revises: 87e49cd60f27



Create Date: 2025-10-11 15:43:38.493656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd4fb2cee067"

down_revision: Union[str, None] = "87e49cd60f27"



branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_variant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("printing_id", sa.Uuid(), nullable=False),
        sa.Column("language_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.ForeignKeyConstraint(
            ["printing_id"],
            ["printing.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "printing_id",
            "language_id",
            name="uq_product_variant_product_printing_language",
        ),
    )
    op.create_index(
        "ix_product_variant_printing_language",
        "product_variant",
        ["printing_id", "language_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_product_id"),
        "product_variant",
        ["product_id"],
        unique=False,
    )
    op.add_column("sku", sa.Column("variant_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_sku_variant_id"), "sku", ["variant_id"], unique=False)
    op.create_foreign_key(
        "fk_sku_variant_id", "sku", "product_variant", ["variant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sku_variant_id", "sku", type_="foreignkey")
    op.drop_index(op.f("ix_sku_variant_id"), table_name="sku")
    op.drop_column("sku", "variant_id")
    op.drop_index(op.f("ix_product_variant_product_id"), table_name="product_variant")
    op.drop_index("ix_product_variant_printing_language", table_name="product_variant")
    op.drop_table("product_variant")
    # ### end Alembic commands ###