"""make_user_id_not_null_and_add_indexes

Revision ID: d396bb092ebc
Revises: a2e15da47a94
Create Date: 2025-07-20 03:10:37.389630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d396bb092ebc"
down_revision: Union[str, None] = "a2e15da47a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory_snapshot", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_index(
        op.f("ix_inventory_snapshot_user_id"),
        "inventory_snapshot",
        ["user_id"],
        unique=False,
    )
    op.alter_column("line_item", "user_id", existing_type=sa.UUID(), nullable=False)
    op.create_index(
        op.f("ix_line_item_user_id"), "line_item", ["user_id"], unique=False
    )
    op.alter_column(
        "line_item_consumption", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_index(
        op.f("ix_line_item_consumption_user_id"),
        "line_item_consumption",
        ["user_id"],
        unique=False,
    )
    op.alter_column("platform", "user_id", existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f("ix_platform_user_id"), "platform", ["user_id"], unique=False)
    op.alter_column("transaction", "user_id", existing_type=sa.UUID(), nullable=False)
    op.create_index(
        op.f("ix_transaction_user_id"), "transaction", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_user_id"), table_name="transaction")
    op.alter_column("transaction", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index(op.f("ix_platform_user_id"), table_name="platform")
    op.alter_column("platform", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index(
        op.f("ix_line_item_consumption_user_id"), table_name="line_item_consumption"
    )
    op.alter_column(
        "line_item_consumption", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_index(op.f("ix_line_item_user_id"), table_name="line_item")
    op.alter_column("line_item", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index(
        op.f("ix_inventory_snapshot_user_id"), table_name="inventory_snapshot"
    )
    op.alter_column(
        "inventory_snapshot", "user_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
