"""empty message

Revision ID: de92764096d8
Revises: 6702d39d0232
Create Date: 2025-04-27 15:45:38.675174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de92764096d8"
down_revision: Union[str, None] = "6702d39d0232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction", sa.Column("platform_order_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "platform_order_id")
    # ### end Alembic commands ###
