"""make job_id nullable in SKUPriceDataSnapshot

Revision ID: e3c995f34f66
Revises: 4811425b2f6f
Create Date: 2025-05-18 23:37:36.373455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3c995f34f66"
down_revision: Union[str, None] = "4811425b2f6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sku_price_data_snapshot", "job_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sku_price_data_snapshot", "job_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
