"""Add unique constraints for catalog_id and tcgplayer_id to Condition, Printing, and Language tables

Revision ID: ebe681c33b3e
Revises: c75876a39c72
Create Date: 2025-03-20 01:08:40.393078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe681c33b3e'
down_revision: Union[str, None] = 'c75876a39c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_condition_catalog_id_tcgplayer_id', 'condition', ['catalog_id', 'tcgplayer_id'])
    op.create_unique_constraint('uq_language_catalog_id_tcgplayer_id', 'language', ['catalog_id', 'tcgplayer_id'])
    op.create_unique_constraint('uq_printing_catalog_id_tcgplayer_id', 'printing', ['catalog_id', 'tcgplayer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_printing_catalog_id_tcgplayer_id', 'printing', type_='unique')
    op.drop_constraint('uq_language_catalog_id_tcgplayer_id', 'language', type_='unique')
    op.drop_constraint('uq_condition_catalog_id_tcgplayer_id', 'condition', type_='unique')
    # ### end Alembic commands ###
