"""Add ebay_product_id to ProductVariant

Revision ID: f97fa742fb12
Revises: cd4fb2cee067
Create Date: 2025-10-12 00:50:58.213917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f97fa742fb12"
down_revision: Union[str, None] = "cd4fb2cee067"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variant", sa.Column("ebay_product_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_product_variant_ebay_product_id"),
        "product_variant",
        ["ebay_product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_variant_ebay_product_id"), table_name="product_variant"
    )
    op.drop_column("product_variant", "ebay_product_id")
    # ### end Alembic commands ###
