FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /code

COPY requirements.txt requirements-lock.txt ./

COPY ./cron /code/cron
COPY ./core /code/core

RUN uv pip install --system -r requirements.txt

# Use -m cron.tasks.update_catalog_db to target the specific task script
CMD ["python", "-m", "cron.tasks.update_catalog_db"]
