import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { Card } from "@/components/ui/card";
import { SWRConfig } from "swr";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-foreground antialiased">
        <SWRConfig value={{ revalidateOnFocus: false }}>
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-1 flex-col">
              <SiteHeader />
              <main className="flex flex-1 flex-col p-6">{children}</main>
            </div>
          </SidebarProvider>
        </SWRConfig>
      </body>
    </html>
  );
}
