import "./globals.css";
import type { Metadata } from "next";
import { SWRConfig } from "swr";
import { Plus_Jakarta_Sans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/shared/Providers";
import { TopNav } from "@/components/top-nav";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap", // Recommended for performance
  variable: "--font-plus-jakarta-sans", // For use with CSS variables (e.g., Tailwind CSS)
  weight: ["400", "700"], // Or specify a range for variable fonts
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const authState = session?.user
    ? {
        isAuthenticated: true,
        user: {
          id: session.user.id,
          email: session.user.email ?? undefined,
        },
      }
    : { isAuthenticated: false };

  return (
    <html
      lang="en"
      className={`${plusJakartaSans.className} ${plusJakartaSans.variable} dark`}
    >
      <body className="min-h-screen mx-auto">
        <NextTopLoader />
        <Providers>
          <SWRConfig value={{ revalidateOnFocus: false }}>
            <div className="in-h-screen">
              <TopNav authState={authState} />
              <main className="mx-auto max-w-7xl">{children}</main>
            </div>
          </SWRConfig>
        </Providers>
      </body>
    </html>
  );
}
